feature/courses
OpenMined/courses-app pull request #13
Opened 2020-11-29 19:14 UTC by hericlesme

## Description
Please include a summary of the change, the motivation, and any additional context that will help others understand your PR. If it closes one or more open issues, [please tag them as described here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

2020-11-29 20:04 UTC, cereallarceny requested changes

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/App.tsx
> +        <Footer />
Move this above the cookie preferences so that we don't have z-index issues.

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/components/CourseCard.tsx
> +  const { title, visual, cost, level, length, slug } = content;
Have a blank space after this line

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/components/CourseCard.tsx
> +  const { title, visual, cost, level, length, slug } = content;
Let's also create a constant for some shared styles, these are the ones:

```js
const absoluteOpacityStyles = {
  position: "absolute",
  top: 0,
  left: 0,
  width: "100%",
  height: "100%",
  transitionProperty: "opacity",
  transitionDuration: "slow",
  transitionTimingFunction: "ease-in-out"
};
```

Apply this to the `<Box>` that needs it, as well as the two `<Image>`s that need it. Pay attention to the `zIndex` and `opacity` props that are different between them.

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/components/CourseCard.tsx
> +                opacity: 0,
Same line please

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/components/Footer.tsx
> +import GridContainer from './GridContainer';
Space above

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/components/Footer.tsx
> +import content from '../content/footer';
Another space above

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/components/Footer.tsx
> +export default ({ ...props }) => {
No need to destructure. Just do `(props)`

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/components/Footer.tsx
> +  const { about, catalog, resources, bottom } = content;
Combine these destructures into one: 

```js
const {
  about,
  catalog,
  resources,
  bottom: { copyright, terms_and_conditions, privacy_policy }
} = content;
```

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/components/Footer.tsx
> +          justifyContent="space-between"
`justify`

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/components/Footer.tsx
> +  return (
Don't write `return` here, just wrap in parentheses.

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/components/Footer.tsx
> +  const { about, catalog, resources, bottom } = content;
Also destructure `about` if possible

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/components/Header.tsx
> +      zIndex={3}
We should leave this at `1` and fix the other components instead. I'm a bit fan of leaving `zIndex` to be determined by the order of the DOM elements, and NOT some random number.

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/components/Header.tsx
> +      zIndex={3}
https://chakra-ui.com/guides/z-index

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/content/footer.ts
> +      text: 'OpenMined.org',
We need the right arrow icon like in the designs here

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/content/footer.ts
> +      'Located at the intersection of privacy & AI, we are an open-source community of over 8000+ researchers, engineers, mentors and enthusiasts committed to making a fairer more prosperous world.',
`over 10,000` - no plus, with a comma for the thousands separator

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/content/footer.ts
> +        link: '#',
Fill these in manually, so that the links work. Don't use Sanity here.

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/content/footer.ts
> +        name: 'Course Name 1',
Should be called `title`

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/content/footer.ts
> +        link: '#',
Fill these links in - you know all of them. :)

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/content/footer.ts
> +        link: '#',
Make this https://placements.openmined.org

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/content/footer.ts
> +      link: '/terms-and-conditions',
Make this `/tos`

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/content/footer.ts
> +    privacy_policy: { name: 'Privacy Policy', link: '/privacy-policy' },
`/policy`

Also make this on a new line

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/content/footer.ts
> +    copyright: `Copyright ${new Date().getFullYear()} OpenMined`,
Make sure to add the copyright symbol, look at https://github.com for how to do this

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/routes/courses/Sidebar.tsx
> +  VStack,
Just use `<Stack>` and define a direction

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/routes/courses/Sidebar.tsx
> +  const filters = [
Don't define these in the sidebar, define them in the parents and then pass them.

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/routes/courses/Sidebar.tsx
> +            {' '}
Don't have an empty space here, use margin left

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/routes/courses/Sidebar.tsx
> +            {' '}
Or nothing...

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/routes/courses/index.tsx
> +import Sidebar from './Sidebar';
This import needs to be higher.

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/routes/courses/index.tsx
> +  const currKeyword = useRef();
If we can do this with a reference, it would be better.

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/routes/courses/index.tsx
> +    if (skillLevel && course.level) hasSkillLevel = skillLevel === course.level;
Make this a ternary assignment on the variable

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/routes/courses/index.tsx
> +      hasTopic = topics.some((topic) => course.topics.includes(topic));
Same

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/routes/courses/index.tsx
> +      hasLanguages = languages.some((language) =>
Same

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/routes/courses/index.tsx
> +    if (skillLevel && course.level) hasSkillLevel = skillLevel === course.level;
And make these all `const`'s

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/routes/courses/index.tsx
> +    if (currKeyword.current === undefined) return;
`if(!currKeyword.current)`

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/routes/courses/index.tsx
> +    const val = currKeyword.current!.value;
Let's give all of this some more space... I can't read this since it's too compact.

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/routes/courses/index.tsx
> +      return;
Always space out returns

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/routes/courses/index.tsx
> +  const removeKeyword = (keywordIndex) => {
Always space out multi-line const declaractions

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/routes/courses/index.tsx
> +  const clearFilters = () => {
Same

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/routes/courses/index.tsx
> +              {...{
Have these as props, don't destructure - it's confusing

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/routes/courses/index.tsx
> +                _placeholder={{ color: 'gray.600' }}
Don't make this many specific design overrides for a single input. Either put it in the theme all inputs or let it be consistent and believe that the designer made a mistake. ;)

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/routes/courses/index.tsx
> +            <datalist id="courses">
Whatever this is - don't do it. Pick a different component.

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/routes/courses/index.tsx
> +            <datalist id="courses">
Also, no need for `id` or `className` anywhere except in rare situations.

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/routes/courses/index.tsx
> +  const TAG_BG_COLOR = 'rgba(0, 162, 183, 0.25)';
Remove this line

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/routes/courses/index.tsx
> +                      bgColor={TAG_BG_COLOR}
Pick one of the existing tag backgrounds, don't stick to the design

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/routes/courses/Sidebar.tsx
> +          bgColor={ALERT_BG_COLOR}
Pick the closest color, don't stick to the designs... keep this clean.

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/routes/courses/Sidebar.tsx
> +  const ALERT_BG_COLOR = 'rgba(0, 162, 183, 0.25)';
Remove this

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/routes/homepage/Learn.tsx
> +          {!loading &&
Remove this and put up top: `if(loading) return null;`

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/routes/courses/index.tsx
> +              {!loading &&
Remove this and put up top: `if(loading) return null;`

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/routes/homepage/Learn.tsx
> +                onClick={console.log}
??? Remove this.

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/routes/index.tsx
> +const Courses = lazy(() => import('./courses'));
First of all, move this above `NoMatch` so that we keep the EXACT same order in the export below.

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/routes/index.tsx
> +const Courses = lazy(() => import('./courses'));
And second of all, move this to a folder under `/courses/search`

2020-11-29 20:04 UTC, cereallarceny commented on apps/courses/src/routes/index.tsx
> +const Courses = lazy(() => import('./courses'));
Also rename the component to be called `CoursesSearch`.

2020-11-29 20:08 UTC, cereallarceny commented
1. Push changes to the same branch (`feature/courses`)
2. @cereallarceny to do visual overview
3. Merge
4. Do review of TOS and PP PR
5. @cereallarceny to do visual overview of that PR
6. Merge

2020-11-30 14:48 UTC, cereallarceny commented
**Footer**
- [ ] Replace absolute links for courses in footer with relative links
- [ ] Change title from "Catalog" to "Courses"
- [ ] Github should be spelled "Github" with no capital "H"
- [ ] Only have the target=_blank and rel=noopen for the external links... which should only be under "resources"
- [ ] Have Courses and Resources next to each other on medium up

**Courses**
- [ ] On mobile up, make sure it follows 100% width with the grid container. Right now it looks like the mobile width of the content is about 80%.
- [ ] Make the margin on the search to be nothing, however, you should actually add margin to the top of the search on mobile
- [ ] Make the breakpoint for the sidebar to appear horizontal to the results to be later (if it's medium, make it large).
- [ ] Let's also swap the search input for the "lg" size, instead of the default "md"
- [ ] When focusing on the input, the icon to the right doesn't also have the background and border color as the input. This means that you're doing something incorrectly according to Chakra.
- [ ] Make the sidebar scroll with you after it breaks
- [ ] The "no results" text is typed incorrectly. The title should read: "Sorry, there are no search results for that query" and remove the description.
- [ ] Remove the tags from the search altogether and have the search be "fuzzy find" as you're typing... don't wait to press enter or click any button
- [ ] For the XL size screen, let's just do a 2 column result, don't ever go to 3 or beyond

2020-11-30 17:18 UTC, hericlesme commented
Done, except for the focus:
>  When focusing on the input, the icon to the right doesn't also have the background and border color as the input. This means that you're doing something incorrectly according to Chakra.

Maybe an issue in chakra `1.0.0-rc.5`.

2020-11-30 17:55 UTC, cereallarceny approved these changes

2020-11-30 17:55 UTC, merged