Add typings for Course root pages
OpenMined/courses-app pull request #29
Opened 2020-12-21 20:50 UTC by ITsolution-git

## Description
Add Types for firebase data structure and component's proptypes

## Affected Dependencies
None

## How has this been tested?
None

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

2020-12-21 22:01 UTC, cereallarceny requested changes

2020-12-21 22:01 UTC, cereallarceny commented on apps/courses/src/components/Header.tsx
> +import { OpenMinded } from '@openmined/shared/types';
Hahaha our name is "OpenMined", not "OpenMinded". That's Open + Mined (to mine something in the past tense), not to be confused with "Mind" or "Mine".

2020-12-21 22:01 UTC, cereallarceny commented on libs/shared/types/src/index.ts
> +    started_at: firebase.firestore.DocumentReference;
Should be `firebase.firestore.Timestamp`

2020-12-21 22:01 UTC, cereallarceny commented on libs/shared/types/src/index.ts
> +    completed_at?: firebase.firestore.DocumentReference;
Same here

2020-12-21 22:05 UTC, ITsolution-git commented on apps/courses/src/components/Header.tsx
> +import { OpenMinded } from '@openmined/shared/types';
Urgg, sorry I am a dumb. (that's why I wear glasses...) I thought it was open-minded - empathetic!!

2020-12-22 10:38 UTC, cereallarceny approved these changes

2020-12-22 10:48 UTC, merged